### ISSUE TITLE
Not receiving perk points when leveling up from Level 50-56 [BUG]

### ISSUE THREAD

**Issue by katsmurph** [Oghma-Infinium/Fahluaan#4]
I haven't received any perk points after level 50 and I just hit level 56. 

I've tried sleeping, working on skills that weren't high and playing the skills, ie using restoration in battle. I tried removing gear with boons and i've looked high and low on the internet but I haven't heard or seen this problem. I'm about to go back to level 50 and see if I do it again from there if it will work.

To reproduce, you have to level up...that's it. Is it possible it's working as it supposed to? If so, how long could this go on...it's very frustrating.

I would expect to receive a perk point with each level up. I noticed that I got extra perk points with specific quests but until level 50, I'd received at least 1 perk point at every level gained.

Windows 11
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor
NVDIA GEForce GTX 1060
Samsung SDD 970 EVO Plus 2TB 
Page file is as per the Fahluaan configuration directions
I downloaded the list on 12/27/23

**Comment by aljoxo** [comment]
This is not a bug, the gameplay guide also states you only receive 54 perks from leveling.

It is fully intentional that you no longer receive perk points after hitting level 50.

**Comment by katsmurph** [comment]
Update: I played through my save before I hit level 50, starting at level 48. I received a perk point with level 49 and level 50, but at level 51 did not get one.

**Comment by aljoxo** [comment]
read what I typed.

**Comment by katsmurph** [comment]
Sorry, i didn't see it before my comment. I saw that the gameplay guide said that but it wasn't clear that it would be the final perk. I see.

**Comment by katsmurph** [comment]
Sorry, i didn't see it before my comment. I saw that the gameplay guide said that but it wasn't clear that it would be the final perk. I see.
