### ISSUE TITLE
Missing warehouse door in Solitude

### ISSUE THREAD

**Issue by TazerReloaded** [Oghma-Infinium/Fahluaan#7]
**Describe the bug**
The warehouse door in Solitude harbor is missing, see screenshot.

**To Reproduce**
1. Go to Solitude harbor
2. Look at East Empire Company Warehouse

**Screenshots**
![enb2024_2_16_00_03_39](https://github.com/Oghma-Infinium/Fahluaan/assets/26871986/7974813c-d9fe-4a3b-88f7-579ff777def8)

**Technical (please complete the following information):**
 - OS: Windows 11
 - CPU: i5-14600
 - GPU: RTX 4070 Super 12GB
 - RAM: 32GB
 - Type of Drive: NVME M.2
 - Pagefile Size: 32768MB
 - List Version: 2.0.3

**Additional context**
I verified my installation with Wabbajack. No custom changes, no additional mods.

**Comment by aljoxo** [comment]
This isn't an issue with the list, it's an issue on your save game, likely caused by DynDOLOD not properly re-enabling the mesh.
